GET http://localhost:8080/api/rss/generate

###
GET http://localhost:8080/api/rss

###
POST http://localhost:8080/api/management/channel
Content-Type: application/json

{
  "link": "https://www.antaranews.com/rss/top-news.xml",
  "category": "PRIVATE",
  "title": "Antara News",
  "language": "ID"
}

###
GET http://localhost:8080/api/management/channel/e610f03da4d542008c951f1f07ef18a4

###
GET http://localhost:8080/api/management/channel

###
PUT http://localhost:8080/api/management/channel/e610f03da4d542008c951f1f07ef18a4
Content-Type: application/json

{
  "link": "https://www.antaranews.com/rss/top-news.xml",
  "category": "PRIVATE",
  "title": "Antara News",
  "language": "ID"
}

###
DELETE http://localhost:8080/api/management/channel/b4bcdc0ad74047468b64d00379275e5f
